import React, { useEffect, useState } from 'react';
import { Building2, Plus, Users } from 'lucide-react';
import { createAssessmentApi, createCohortApi, getCohortsApi, getInstitutionAnalyticsApi } from '../../services/api';
import { useApp } from '../../context/AppContext';
import { Button } from '../../components/common/Button';

export const InstitutionAdmin: React.FC = () => {
  const { authToken } = useApp(); const [analytics, setAnalytics] = useState<any>(); const [cohorts, setCohorts] = useState<any[]>([]); const [message, setMessage] = useState('');
  const [cohort, setCohort] = useState({ name: '', year: '', branch: '', section: '' }); const [assessment, setAssessment] = useState({ title: '', description: '', cohort_id: '', skill: '', prompt: '', optionA: '', optionB: '' });
  const refresh = () => { if (authToken) Promise.all([getInstitutionAnalyticsApi(authToken), getCohortsApi(authToken)]).then(([a, c]) => { setAnalytics(a); setCohorts(c); }).catch(e => setMessage(e.message)); };
  useEffect(refresh, [authToken]);
  const addCohort = async (e: React.FormEvent) => { e.preventDefault(); if (!authToken) return; try { await createCohortApi(authToken, cohort); setCohort({ name: '', year: '', branch: '', section: '' }); refresh(); } catch (e: any) { setMessage(e.message); } };
  const addAssessment = async (e: React.FormEvent) => { e.preventDefault(); if (!authToken) return; try { await createAssessmentApi(authToken, { title: assessment.title, description: assessment.description, cohort_id: assessment.cohort_id, skill: assessment.skill, questions: [{ id: 'q1', prompt: assessment.prompt, options: [assessment.optionA, assessment.optionB], correct_option: 0, skill: assessment.skill }] }); setMessage('Assessment published to the selected cohort.'); setAssessment({ title: '', description: '', cohort_id: '', skill: '', prompt: '', optionA: '', optionB: '' }); refresh(); } catch (e: any) { setMessage(e.message); } };
  return <div className="space-y-8 pb-12"><div><h1 className="text-3xl font-extrabold text-white">Institution Admin</h1><p className="text-xs text-slate-400">Tenant-scoped cohorts, assessments, and participation analytics.</p></div>{message && <p className="p-3 bg-indigo-500/10 rounded-xl text-indigo-200">{message}</p>}<div className="grid sm:grid-cols-3 gap-4">{[['Students', analytics?.total_students], ['Cohorts', analytics?.cohort_count], ['Submissions', analytics?.assessment_submissions]].map(([label, value]) => <div key={String(label)} className="glass-panel rounded-2xl p-5 border border-white/10"><p className="text-slate-400 text-sm">{label}</p><p className="text-3xl font-bold text-white">{value ?? '—'}</p></div>)}</div><div className="grid lg:grid-cols-2 gap-6"><form onSubmit={addCohort} className="glass-panel p-6 rounded-2xl border border-white/10 space-y-3"><h2 className="text-white font-bold flex gap-2"><Users className="w-5 h-5" />Create cohort</h2>{(['name','year','branch','section'] as const).map(key => <input key={key} required={key !== 'section'} placeholder={key.replace('_',' ')} value={cohort[key]} onChange={e => setCohort({ ...cohort, [key]: e.target.value })} className="w-full p-3 rounded-xl bg-white/5 text-white border border-white/10" />)}<Button type="submit" variant="glow" leftIcon={<Plus className="w-4 h-4" />}>Create cohort</Button></form><form onSubmit={addAssessment} className="glass-panel p-6 rounded-2xl border border-white/10 space-y-3"><h2 className="text-white font-bold flex gap-2"><Building2 className="w-5 h-5" />Publish assessment</h2><input required placeholder="Title" value={assessment.title} onChange={e => setAssessment({...assessment,title:e.target.value})} className="w-full p-3 rounded-xl bg-white/5 text-white border border-white/10" /><select required value={assessment.cohort_id} onChange={e => setAssessment({...assessment,cohort_id:e.target.value})} className="w-full p-3 rounded-xl bg-[#12141d] text-white border border-white/10"><option value="">Select cohort</option>{cohorts.map(c => <option key={c.id} value={c.id}>{c.name} · {c.branch}</option>)}</select>{(['skill','prompt','optionA','optionB'] as const).map(key => <input key={key} required placeholder={key === 'optionA' ? 'Correct option' : key === 'optionB' ? 'Alternative option' : key} value={assessment[key]} onChange={e => setAssessment({...assessment,[key]:e.target.value})} className="w-full p-3 rounded-xl bg-white/5 text-white border border-white/10" />)}<Button type="submit" variant="glow">Publish</Button></form></div></div>;
};
