import {
  UserProfile,
  IdentityTwin,
  LearningResource,
  Opportunity,
  TaskItem,
  ReflectionEntry,
  NotificationItem,
  AnalyticsSummary,
} from '../types';

export const mockUser: UserProfile = {
  id: 'usr-101',
  name: 'Alex Rivera',
  email: 'alex.rivera@growthos.ai',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
  title: 'Principal AI Architect & Founder Aspirant',
  bio: 'Building autonomous AI systems while mastering deep tech leadership & cognitive endurance.',
  dreamRole: 'Founder & Chief AI Officer at Next-Gen AI Lab',
  level: 14,
  experienceLevel: 'Senior (6+ Years)',
  location: 'San Francisco, CA (Hybrid)',
  streak: 24,
  growthScore: 92,
  identityScore: 88,
  joinedDate: 'January 2026',
  achievements: [
    {
      id: 'ach-1',
      title: 'Identity Architect',
      description: 'Maintained >85% alignment with Dream Identity for 30 consecutive days.',
      icon: 'Sparkles',
      unlockedAt: 'July 2026',
      category: 'Identity',
    },
    {
      id: 'ach-2',
      title: 'Deep Focus Master',
      description: 'Completed 100+ deep work learning blocks with zero burnout flags.',
      icon: 'Zap',
      unlockedAt: 'June 2026',
      category: 'Productivity',
    },
    {
      id: 'ach-3',
      title: 'Curator Elite',
      description: 'Applied insights from over 50 top-tier research papers & video lectures.',
      icon: 'BookOpen',
      unlockedAt: 'May 2026',
      category: 'Learning',
    },
    {
      id: 'ach-4',
      title: 'Hackathon Champion',
      description: 'Secured top 3 placement in AI Agentic Systems Global Hackathon.',
      icon: 'Trophy',
      unlockedAt: 'April 2026',
      category: 'Opportunities',
    },
  ],
  certificates: [
    {
      id: 'cert-1',
      title: 'Advanced Multi-Agent Architectures with LangGraph & Autonomous Systems',
      issuer: 'DeepLearning.AI & OpenAI Labs',
      date: 'June 2026',
      credentialUrl: '#',
      skills: ['LangGraph', 'Agentic Workflows', 'Multi-Agent Swarms', 'Python'],
    },
    {
      id: 'cert-2',
      title: 'System Design for AI Scale & High Performance Computing',
      issuer: 'Vercel Academy',
      date: 'May 2026',
      credentialUrl: '#',
      skills: ['Distributed Systems', 'Edge Compute', 'Vector Databases'],
    },
  ],
};

export const mockIdentityTwin: IdentityTwin = {
  currentArchetype: 'Specialist AI Engineer',
  dreamArchetype: 'Visionary AI Founder & Systems Architect',
  alignmentPercentage: 88,
  driftScore: 12, // 12% drift (very low risk)
  coreValues: ['Technical Mastery', 'Autonomy', 'Deep Impact', 'Continuous Growth'],
  dreamValues: ['Global Scale', 'Empathetic Leadership', 'Radical Innovation', 'Financial Freedom'],
  skills: [
    { skill: 'Agentic AI Architecture', currentLevel: 90, targetLevel: 98, category: 'AI/ML' },
    { skill: 'Product Vision & Strategy', currentLevel: 72, targetLevel: 95, category: 'Leadership' },
    { skill: 'Public Speaking & Pitching', currentLevel: 60, targetLevel: 90, category: 'Communication' },
    { skill: 'System Design & Scalability', currentLevel: 85, targetLevel: 95, category: 'Engineering' },
    { skill: 'Cognitive Endurance & Habit Regularity', currentLevel: 88, targetLevel: 95, category: 'Personal' },
    { skill: 'Venture Capital & Unit Economics', currentLevel: 50, targetLevel: 85, category: 'Business' },
  ],
  insights: [
    {
      id: 'ins-1',
      type: 'positive',
      title: 'Rapid Momentum in Agentic Systems',
      description: 'Your skill mastery in LangGraph & Multi-Agent systems increased by 18% this month.',
    },
    {
      id: 'ins-2',
      type: 'suggestion',
      title: 'Venture Capital Knowledge Gap',
      description: 'To reach your Founder Archetype, spend 3 hours this week reviewing SaaS unit economics & fundraising strategies.',
    },
    {
      id: 'ins-3',
      type: 'warning',
      title: 'Slight Burnout Indicator on Weekends',
      description: 'Late night coding sessions past 1:00 AM increase drift by 4%. Schedule rest windows.',
    },
  ],
  timeline: [
    { date: 'Jan 2026', milestone: 'Baseline Identity Twin Created', alignment: 62 },
    { date: 'Mar 2026', milestone: 'Completed Deep RL & Agentic Curriculum', alignment: 74 },
    { date: 'May 2026', milestone: 'First Global Hackathon Win', alignment: 81 },
    { date: 'Jul 2026', milestone: 'Identity Drift Reduced to 12%', alignment: 88 },
  ],
};

export const mockLearningResources: LearningResource[] = [
  {
    id: 'lr-1',
    title: 'Building Autonomous Multi-Agent Swarms with LangGraph & Memory Pools',
    type: 'course',
    author: 'Harrison Chase & DeepMind Labs',
    platform: 'GrowthOS Academy',
    duration: '4h 30m',
    difficulty: 'Advanced',
    category: 'Agentic AI',
    rating: 4.9,
    tags: ['LangGraph', 'Multi-Agent', 'Python', 'Mem0'],
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=500',
    link: '#',
    isBookmarked: true,
    isLiked: true,
    progressPercentage: 75,
  },
  {
    id: 'lr-2',
    title: 'The Founder’s Playbook: Zero to Series A for Deep Tech Startups',
    type: 'book',
    author: 'Elad Gil & Marc Andreessen',
    platform: 'Audiobook / Digital Copy',
    duration: '6h 15m',
    difficulty: 'Intermediate',
    category: 'Leadership & Business',
    rating: 4.8,
    tags: ['Startup', 'Fundraising', 'Strategy'],
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=500',
    link: '#',
    isBookmarked: false,
    isLiked: true,
    progressPercentage: 40,
  },
  {
    id: 'lr-3',
    title: 'State of AI 2026: Reasoning Models, Multimodal Memory & Spatial Computing',
    type: 'paper',
    author: 'OpenAI & Stanford AI Research Group',
    platform: 'ArXiv Open Research',
    duration: '45m read',
    difficulty: 'Advanced',
    category: 'Research',
    rating: 5.0,
    tags: ['LLMs', 'Multimodal', 'Memory Retrieval'],
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=500',
    link: '#',
    isBookmarked: true,
    isLiked: true,
    progressPercentage: 100,
  },
  {
    id: 'lr-4',
    title: 'Mastering Pitch Deck Storytelling & Executive Presence for Founders',
    type: 'video',
    author: 'Y Combinator Partner Series',
    platform: 'YouTube Tech',
    duration: '1h 10m',
    difficulty: 'Intermediate',
    category: 'Communication',
    rating: 4.7,
    tags: ['Pitching', 'Public Speaking', 'Venture Capital'],
    imageUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=500',
    link: '#',
    isBookmarked: false,
    isLiked: false,
    progressPercentage: 10,
  },
  {
    id: 'lr-5',
    title: 'Substack AI Deep Dives: Building Vector Databases from Scratch in Rust',
    type: 'article',
    author: 'Chip Huyen',
    platform: 'Substack Tech',
    duration: '25m read',
    difficulty: 'Advanced',
    category: 'Engineering',
    rating: 4.9,
    tags: ['Rust', 'Vector DB', 'Search'],
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=500',
    link: '#',
    isBookmarked: true,
    isLiked: true,
    progressPercentage: 90,
  },
  {
    id: 'lr-6',
    title: 'Lex Fridman Podcast: Demis Hassabis on General Intelligence & Bio-AI',
    type: 'podcast',
    author: 'Lex Fridman Podcast',
    platform: 'Spotify / Apple Podcasts',
    duration: '3h 10m',
    difficulty: 'Beginner',
    category: 'AI / Vision',
    rating: 4.9,
    tags: ['AGI', 'Neuroscience', 'Philosophy'],
    imageUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&q=80&w=500',
    link: '#',
    isBookmarked: false,
    isLiked: true,
    progressPercentage: 60,
  },
];

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Global AI Agentic Systems Hackathon 2026',
    organization: 'OpenAI & GrowthOS',
    type: 'hackathon',
    matchScore: 98,
    difficulty: 'Advanced',
    deadline: 'Aug 20, 2026',
    location: 'Virtual / San Francisco',
    skillsRequired: ['LangGraph', 'Python', 'React', 'FastAPI'],
    reward: '$100,000 Grand Prize + VC Office Hours',
    isFavorite: true,
    description: 'Build autonomous agents that solve real-world industry bottlenecks. Judged by top AI founders & researchers.',
    applyUrl: '#',
  },
  {
    id: 'opp-2',
    title: 'Senior AI Engineer in Residence Program',
    organization: 'Benchmark Capital & Founders Fund',
    type: 'internship',
    matchScore: 94,
    difficulty: 'Advanced',
    deadline: 'Sep 01, 2026',
    location: 'San Francisco, CA',
    skillsRequired: ['System Design', 'LLM Fine-Tuning', 'Multi-Agent'],
    reward: '$18,000 / month + Equity Grant',
    isFavorite: true,
    description: 'Spend 6 months working alongside top portfolio startup founders to build frontier AI products.',
    applyUrl: '#',
  },
  {
    id: 'opp-3',
    title: 'Private Founder Circle: Deep Tech & AI Builders',
    organization: 'Antler & YC Alumni Network',
    type: 'community',
    matchScore: 91,
    difficulty: 'Intermediate',
    deadline: 'Rolling Admission',
    location: 'Global (Discord + Quarterly Retreats)',
    skillsRequired: ['Product Vision', 'AI Engineering'],
    reward: 'Exclusive Network & Co-founder Matching',
    isFavorite: false,
    description: 'A curated community of 250 elite builders building AI infrastructure, agent frameworks, and robotics.',
    applyUrl: '#',
  },
  {
    id: 'opp-4',
    title: '1-on-1 Mentorship: Scaling AI Products from 0 to 1M Users',
    organization: 'Mentors@GrowthOS (Ex-Vercel VP of Eng)',
    type: 'mentor',
    matchScore: 89,
    difficulty: 'Intermediate',
    deadline: 'Aug 15, 2026',
    location: '1-on-1 Video Session',
    skillsRequired: ['Product Strategy', 'Growth Marketing'],
    reward: '3 Private Strategy Sessions',
    isFavorite: false,
    description: 'Get direct feedback on your product architecture, user acquisition loops, and fundraising narrative.',
    applyUrl: '#',
  },
  {
    id: 'opp-5',
    title: 'Frontier AI Summit & Investor Showcase',
    organization: 'TechCrunch & Sequoia Capital',
    type: 'conference',
    matchScore: 86,
    difficulty: 'Beginner',
    deadline: 'Sep 12, 2026',
    location: 'Palace of Fine Arts, SF',
    skillsRequired: ['Networking', 'Pitching'],
    reward: 'VIP Founder Pass ($1,500 value)',
    isFavorite: true,
    description: 'The premier gathering of AI researchers, founders, and angel investors exploring autonomous intelligence.',
    applyUrl: '#',
  },
];

export const mockTasks: TaskItem[] = [
  {
    id: 'tsk-1',
    title: 'Watch LangGraph Multi-Agent Architecture Module 4',
    category: 'Learning',
    priority: 'high',
    time: '09:00 AM',
    duration: '45 mins',
    isCompleted: true,
    date: 'Today',
    type: 'learning',
  },
  {
    id: 'tsk-2',
    title: 'Log Daily Reflection & Mood Check-in',
    category: 'Mindset',
    priority: 'medium',
    time: '01:00 PM',
    duration: '10 mins',
    isCompleted: true,
    date: 'Today',
    type: 'reflection',
  },
  {
    id: 'tsk-3',
    title: 'Review Unit Economics chapter in The Founder Playbook',
    category: 'Business',
    priority: 'high',
    time: '04:00 PM',
    duration: '30 mins',
    isCompleted: false,
    date: 'Today',
    type: 'learning',
  },
  {
    id: 'tsk-4',
    title: 'Submit Hackathon Project Abstract for Global AI Challenge',
    category: 'Opportunity',
    priority: 'high',
    time: '06:30 PM',
    duration: '45 mins',
    isCompleted: false,
    date: 'Today',
    type: 'opportunity',
  },
  {
    id: 'tsk-5',
    title: '30-minute Evening Cardio & Cognitive Recovery Routine',
    category: 'Health Habit',
    priority: 'low',
    time: '08:30 PM',
    duration: '30 mins',
    isCompleted: false,
    date: 'Today',
    type: 'habit',
  },
];

export const mockReflections: ReflectionEntry[] = [
  {
    id: 'ref-1',
    date: 'August 01, 2026',
    mood: 'ecstatic',
    emoji: '🚀',
    prompt: 'What was your biggest technical or mindset breakthrough today?',
    content: 'Implmented state router edges in LangGraph cleanly today. Feeling a tremendous sense of clarity on how multi-agent coordination works without deadlocks. Also maintained my morning deep work streak!',
    sentimentScore: 94,
    keyInsights: ['LangGraph routing mastered', 'Deep focus morning window is essential', 'Energy peak around 10 AM'],
    audioNoteDuration: '01:42',
  },
  {
    id: 'ref-2',
    date: 'July 30, 2026',
    mood: 'thoughtful',
    emoji: '🧠',
    prompt: 'Where did you feel resistance or hesitation today, and how will you overcome it?',
    content: 'Felt slight anxiety when reviewing venture financial models. Realized I have a mental block around accounting terms. Going to reframe it as just another system to architect.',
    sentimentScore: 78,
    keyInsights: ['Financial blocks are reframable as engineering systems', 'Need more beginner-friendly venture capital resources'],
    audioNoteDuration: '00:55',
  },
  {
    id: 'ref-3',
    date: 'July 27, 2026',
    mood: 'happy',
    emoji: '⚡',
    prompt: 'What small habit yielded the highest ROI for your clarity of thought?',
    content: 'Taking a 15-minute phone-free walk right after lunch completely eliminated afternoon brain fog. My focus score jumped 20% in the 2-5 PM block.',
    sentimentScore: 88,
    keyInsights: ['Post-lunch walks increase focus', 'Screen detox boosts afternoon energy'],
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: '🎯 Identity Milestone Reached',
    message: 'Your Identity Alignment with Founder Archetype crossed 88%! You unlocked the Identity Architect Badge.',
    type: 'milestone',
    timeAgo: '10 mins ago',
    isRead: false,
    actionUrl: '/identity-twin',
  },
  {
    id: 'notif-2',
    title: '💡 AI Curator Insight',
    message: 'Based on your recent venture capital reading, we recommended a 1h YC Partner video pitch session.',
    type: 'ai_insight',
    timeAgo: '1 hour ago',
    isRead: false,
    actionUrl: '/learning',
  },
  {
    id: 'notif-3',
    title: '⚡ New 98% Match Opportunity',
    message: 'Global AI Agentic Systems Hackathon deadline is in 19 days. Registration is open.',
    type: 'opportunity',
    timeAgo: '3 hours ago',
    isRead: true,
    actionUrl: '/opportunity',
  },
  {
    id: 'notif-4',
    title: '🔥 24-Day Habit Streak',
    message: 'Awesome consistency! You have logged daily reflections for 24 consecutive days.',
    type: 'task',
    timeAgo: 'Yesterday',
    isRead: true,
    actionUrl: '/reflection',
  },
];

export const mockAnalytics: AnalyticsSummary = {
  growthPredictionScore: 94,
  burnoutRiskPercentage: 14, // 14% (Low)
  consistencyRate: 92,
  learningHoursTotal: 148,
  weeklyHeatmap: [
    { day: 'Mon', hours: 4.5 },
    { day: 'Tue', hours: 6.0 },
    { day: 'Wed', hours: 5.5 },
    { day: 'Thu', hours: 7.0 },
    { day: 'Fri', hours: 5.0 },
    { day: 'Sat', hours: 3.5 },
    { day: 'Sun', hours: 2.0 },
  ],
  monthlyProgress: [
    { month: 'Feb', score: 65, burnout: 28 },
    { month: 'Mar', score: 72, burnout: 22 },
    { month: 'Apr', score: 78, burnout: 18 },
    { month: 'May', score: 84, burnout: 25 },
    { month: 'Jun', score: 89, burnout: 16 },
    { month: 'Jul', score: 94, burnout: 14 },
  ],
  radarSkills: [
    { subject: 'AI Architecture', current: 90, target: 98, fullMark: 100 },
    { subject: 'Product Strategy', current: 72, target: 95, fullMark: 100 },
    { subject: 'Public Speaking', current: 60, target: 90, fullMark: 100 },
    { subject: 'System Design', current: 85, target: 95, fullMark: 100 },
    { subject: 'Cognitive Recovery', current: 88, target: 95, fullMark: 100 },
    { subject: 'Venture Capital', current: 50, target: 85, fullMark: 100 },
  ],
};
